name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
  CARGO_HOME: ${{ github.workspace }}/src-tauri

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - with:
        path: ${{ env.CARGO_HOME }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
