name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
  CARGO_HOME: ${{ github.workspace }}/src-tauri

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install glib
      run: sudo apt-get install libgtk-3-dev libsoup-3.0
    - name: Build
      run: cd src-tauri; cargo build --verbose
    - name: Run tests
      run: cd src-tauri; cargo test --verbose
