name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install glib
      run: sudo apt-get install libgtk-3-dev libsoup-3.0-0 libjavascriptcoregtk-4.1-0 libwebkit2gtk-4.1-0
    - name: Build
      run: cargo build --manifest-path src-tauri/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path src-tauri/Cargo.toml --verbose
